# Site settings
baseweb: "" # the subpath of your site, e.g. /blog
web: "" # the base hostname & protocol for your site
collections:
  work:
    output: true
  events:
    output: true
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
      header-text: white
      weight: 5
  - scope:
      path: ""
      type: events
    values:
      layout: work
      header-text: white
      weight: 5

# Build settings
markdown: kramdown
plugins:
   - jemoji
   - jekyll-redirect-from

# Metadata
keywords: "web developer, designer, new delhi, ethical hacker"

# Third party services
# google-fonts: "Source+Sans+Pro:400,700,900"
# google-fonts-subsets: "latin"

typekit: "xmd5huf"

# Commonly used lingo
title: "$root 🌳"
location: "New Delhi, India"
email: contact@example.com
description: > # this means to ignore newlines until the next colon
  Hey there! I'm a interactive digital experience web developer and ethical hacker from NITW!
instagram: aakashkumar074
github: Aakash074
facebook: aakash074

# Offline debug flag
dev: false
